ALTER TABLE approval_requests
  ADD COLUMN IF NOT EXISTS required_approvals INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS approval_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS denial_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reviews JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE break_glass_requests
  ADD COLUMN IF NOT EXISTS required_approvals INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS approval_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS denial_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reviews JSONB NOT NULL DEFAULT '[]'::jsonb;
