replicaCount: 1

app:
  environment: development
  logLevel: debug
  bootstrapFromFiles: true
  sandboxInjectionEnabled: true
  sandboxCommandAllowlist: /usr/bin/env,/usr/local/bin/node,/usr/bin/node

postgresql:
  storageSize: 2Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
