{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keylore.postgresSecretName" . }}
  labels:
    {{- include "keylore.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
{{- end }}
